site_name: EA Powertools Governed Metrics Service
pages:
- Home: 'index.md'
- User-Guide: 
     - 'Governed Metrics Service Introduction' : 'user-guide/intro.md'
     - 'Governed Metrics Service Prerequisites' : 'user-guide/prereqs.md'
     - 'Qlik Sense Configuration' : 'user-guide/qsconfig.md'
     - 'Installation' : 'user-guide/install.md'
     - 'Testing Goverened Metrics Service' : 'user-guide/interface.md'
- Governed Metrics Service API: 'gmsapi.md'
- About: 'about.md'
theme: readthedocs
